name: CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: node_modules/
                  key: ${{ hashFiles('package-lock.json') }}
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - run: npm ci
            - run: npm run build
            - run: cp .github/CNAME out
            - uses: xu-cheng/latex-action@v2
              with:
                  latexmk_use_xelatex: true
                  working_directory: private/CV_en
                  root_file: main.tex
            - uses: xu-cheng/latex-action@v2
              with:
                  latexmk_use_xelatex: true
                  working_directory: private/CV_de
                  root_file: main.tex
            - uses: xu-cheng/latex-action@v2
              with:
                  latexmk_use_xelatex: true
                  working_directory: private/CL_en
                  root_file: main.tex
            - uses: xu-cheng/latex-action@v2
              with:
                  latexmk_use_xelatex: true
                  working_directory: private/CL_de
                  root_file: main.tex
            - run: cp private/CV_en/main.pdf out/assets/Mohammad_Hossein_Nemati_CV_en.pdf
            - run: cp private/CV_de/main.pdf out/assets/Mohammad_Hossein_Nemati_CV_de.pdf
            - run: cp private/CL_en/main.pdf out/assets/Mohammad_Hossein_Nemati_CL_en.pdf
            - run: cp private/CL_de/main.pdf out/assets/Mohammad_Hossein_Nemati_CL_de.pdf
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: out

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/deploy-pages@v4
              id: deployment
