name: CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: node_modules/
                  key: ${{ hashFiles('package-lock.json') }}
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
            - run: npm ci
            - run: npm run build
            - run: cp .github/CNAME out
            - run: curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.6/gomplate_linux-amd64
            - run: chmod 755 /usr/local/bin/gomplate && gomplate
            - uses: xu-cheng/latex-action@v2
              with:
                  latexmk_use_xelatex: true
                  working_directory: private/CV
                  root_file: main.tex
            - run: cp private/CV/main.pdf out/assets/CV.pdf
            - uses: actions/upload-artifact@v3
              with:
                  name: public
                  path: out

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo Test

    release:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: public
                  path: out
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
