name: CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: node_modules/
                  key: ${{ hashFiles('package-lock.json') }}
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
            - run: npm ci
            - run: npm run build
            - run: cp .github/CNAME out
            - uses: xu-cheng/latex-action@v2
              with:
                  latexmk_use_xelatex: true
                  working_directory: private/CV
                  root_file: main.tex
            - run: cp private/CV/main.pdf out/assets/CV.pdf
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: out

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/deploy-pages@v4
              id: deployment
