name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          version: 2026.5.7
      - uses: actions/cache@v5
        with:
          path: node_modules/
          key: ${{ hashFiles('package-lock.json') }}

      - run: mise run init
      - run: mise run build

      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: private/CV_en
          latexmk_use_xelatex: true
      - run: cp private/CV_en/main.pdf out/assets/Hoomaan_Nemati_CV_en.pdf

      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: private/CV_de
          latexmk_use_xelatex: true
      - run: cp private/CV_de/main.pdf out/assets/Hoomaan_Nemati_CV_de.pdf

      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: private/CL_en
          latexmk_use_xelatex: true
      - run: cp private/CL_en/main.pdf out/assets/Hoomaan_Nemati_CL_en.pdf

      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: private/CL_de
          latexmk_use_xelatex: true
      - run: cp private/CL_de/main.pdf out/assets/Hoomaan_Nemati_CL_de.pdf

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
